{% macro standardize_weather(column_name) %}
case
    when lower({{ column_name }}) like '%clear%' then 'Clear/Sunny'
    when lower({{ column_name }}) like '%sun%' then 'Clear/Sunny'
    when lower({{ column_name }}) like '%cloud%' then 'Cloudy'
    when lower({{ column_name }}) like '%overcast%' then 'Cloudy'
    when lower({{ column_name }}) like '%fog%' then 'Foggy'
    when lower({{ column_name }}) like '%mist%' then 'Foggy'
    when lower({{ column_name }}) like '%haze%' then 'Foggy'
    when lower({{ column_name }}) like '%smog%' then 'Foggy'
    when lower({{ column_name }}) like '%rain%' then 'Rain'
    when lower({{ column_name }}) like '%drizzle%' then 'Rain'
    when lower({{ column_name }}) like '%sprinkl%' then 'Rain'
    when lower({{ column_name }}) like '%wet roadway%' then 'Rain'
    when lower({{ column_name }}) like '%snow%' then 'Snow'
    when lower({{ column_name }}) like '%ice%' then 'Snow'
    when lower({{ column_name }}) like '%hail%' then 'Snow'
    when lower({{ column_name }}) like '%sleet%' then 'Snow'
    when lower({{ column_name }}) like '%dust%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%sand%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%dirt%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%smoke%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%ash%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%fire%' then 'Dust/Smoke'
    when lower({{ column_name }}) like '%wind%' then 'Windy'
    when lower({{ column_name }}) like '%storm%' then 'Windy'
    when lower({{ column_name }}) like '%parking%' then 'Indoor'
    when lower({{ column_name }}) like '%garage%' then 'Indoor'
    when lower({{ column_name }}) like '%tunnel%' then 'Indoor'
    when lower({{ column_name }}) like '%underground%' then 'Indoor'
    when lower({{ column_name }}) like '%covered%' then 'Indoor'
    when lower({{ column_name }}) like '%unknown%' then 'Unknown or Other'
    when lower({{ column_name }}) like '%unk%' then 'Unknown or Other'
    when lower({{ column_name }}) like '%other%' then 'Unknown or Other'
    when lower({{ column_name }}) like '%undetermined%' then 'Unknown or Other'
    else 'Unknown or Other'
end
{% endmacro %}
