version: 2

sources:
  - name: crashes
    database: ccrs-dashboard
    schema: crashes

    tables:
      - name: crashes_all

models:
  - name: stg_crashes_all
    description: "Staging model for CCRS crashes_all"
    columns:
      - name: collision_id
        description: "The unique identifier of the crash report"
        tests:
          - not_null
          - unique
      - name: report_number
        description: "The unique identifier of the crash report within one NCIC, but it's not unique across California"
      - name: report_version
        description: "Version of the crash report submitted"
        tests:
          - not_null
      - name: preliminary_status
        description: "When, due to unusual circumstances, the crash investigation cannot be submitted to the CHP within 15 working days, the preliminary investigation shall include at minimum (1) Number and names of involved parties (2) Injuries (3) A scene description (4) Summary of sequences of events that led to the crash"
        tests:
          - accepted_values:
              values: ['Preliminary', 'Final', 'Unknown']
      - name: ncic_code
        description: "A four numerical value assigned by the DOJ (Dept of Justice)"
      - name: crash_date
        description: "Crash date extracted from crash_date_time (YYYY-MM-DD)"
        tests:
          - not_null
      - name: crash_time
        description: "Crash / collision time using a 24-hour clock"
      - name: beat
        description: "Assigned patrol area. The number may be 1-3 digits"
      - name: city_id
        description: "Unique city identifer. Used within CCRS system for internal storage"
      - name: city_code
        description: "Unique code of city where the crash occurred"
      - name: city_name
        description: "Name of city where crash occurred"
      - name: county_code
        description: "Unique code of county where crash occurred"
      - name: is_city_active
        description: "Defined by CHP whether the city is valid or not in the CCRS database"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: is_city_incorporated
        description: "As defined by the state of California, an area that has it's own municipal government"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: collision_description_1
        description: "Description of the collision (e.g. side swip, rear end, hit object)"
        tests:
          - accepted_values:
              values: ['Rear End', 'Side Swipe', 'Hit Object', 'Broadside', 'Head-On', 'Overturned', 'Other', 'Vehicle/Pedestrian', 'Unknown']
      - name: collision_description_2
        description: "Additional description of the collision (e.g. side swip, rear end, hit object)"
      - name: day_of_week
        description: "Day of the week that the crash occurred on"
        tests:
          - accepted_values:
              values: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
      - name: is_dispatch_notified
        description: "The day of the week when the crash occurred"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown', 'Not Applicable']
      - name: hit_and_run
        description: "Whether or not the crash was a hit and run and if it was a misdemeanor or felony"
        tests:
          - accepted_values:
              values: ['Felony', 'Misdemeanor', 'None']
      - name: is_deleted
        description: "Whether or not crash was deleted from the CCRS database."
      - name: is_highway_related
        description: "If a crash happened on a highway or not"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: is_tow_away
        description: "If vehicles involved in the crash were towed away or not"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: judicial_district
        description: "Judicial district where the crash occurred"
      - name: motor_vehicle_involved_with_crash_description_1
        description: "Description of the motor vehicle or object involved with the crash"
        tests:
          - accepted_values:
              values: ['Other Motor Vehicle','Fixed Object','Parked Motor Vehicle','Non-Collision','Other Object','Pedestrian','Bicycle','Animal','Motor Vehicle On Other Roadway','Train','Unknown']
      - name: motor_vehicle_involved_with_crash_description_2
        description: "Additional description of the motor vehicle or object involved with the crash"
      - name: number_injured
        description: "Number injured in the crash"
      - name: number_killed
        description: "Number killed in the crash"
      - name: weather_1
        description: "Weather condition at the time of the crash"
        tests:
          - accepted_values:
              values: ['Clear/Sunny', 'Cloudy', 'Foggy', 'Rain', 'Snow', 'Dust/Smoke', 'Windy', 'Indoor', 'Unknown or Other']
      - name: weather_2
        description: "Additional weather condition at the time of the crash"
        tests:
          - accepted_values:
              values: ['Clear/Sunny', 'Cloudy', 'Foggy', 'Rain', 'Snow', 'Dust/Smoke', 'Windy', 'Indoor', 'Unknown or Other', 'Unknown']
      - name: road_condition_1
        description: "Roadway condition at the time of the crash in the traffic lane(s) involved"
        tests:
          - accepted_values:
              values:  ['Holes, Deep Ruts', 'Loose Material on Roadway', 'Obstruction on Roadway', 'Construction or Repair Zone', 'Reduced Roadway Width', 'Flooded', 'Other', 'No Unusual Conditions', 'Unknown']
      - name: road_condition_2
        description: "Second roadway condition at the time of the crash in the traffic lane(s) involved"
        tests:
          - accepted_values:
              values:  ['Holes, Deep Ruts', 'Loose Material on Roadway', 'Obstruction on Roadway', 'Construction or Repair Zone', 'Reduced Roadway Width', 'Flooded', 'Other', 'No Unusual Conditions', 'Unknown']
      - name: lighting_description
        description: "Lighting condition at the time of the crash"
        tests:
          - accepted_values:
              values: ['Daylight', 'Dark - Street Lights', 'Dark - No Street Lights', 'Dusk/Dawn', 'Dark - Street Lights Not Functioning', 'Unknown']
      - name: latitude
        description: "Latitude of crash"
      - name: longitude
        description: "Longitude of crash"
      - name: pedestrian_action_description
        description: "Description of action of pedestrian involved in crash at time of crash if applicable"
        tests:
          - accepted_values:
              values: ['No Pedestrians Involved', 'Crossing In Cross Walk At Intersection', 'In Road - Includes Shoulder', 'Crossing - Not In Crosswalk', 'Not In Road', 'Crossing In Cross Walk - Not At Intersection', 'Approaching/Leaving School Bus', 'Unknown']
      - name: primary_collision_factor_description
        description: "Primary crash factor"
        tests:
          - accepted_values:
              values: ['(Vehicle) Code Violation','Other Improper Driving','Other Than Driver','Unknown','Fell Asleep','Not Stated']
      - name: primary_collision_factor_violation
        description: ""
      - name: primary_collision_party_number
        description: "Used to identify the party who is the primary crash factor"
      - name: primary_road
        description: "Road / location where crash occurred"
      - name: roadway_surface_description
        description: "Description of roadway surface at time of crash"
        tests:
          - accepted_values:
              values: ['Dry','Wet','Snowy/Icy','Slippery (Mud, Oil, etc)','Not Stated']
      - name: secondary_road
        description: "The nearest crossed road where the crash occurred"
      - name: traffic_control_device_description
        description: "Description of traffic control device at crash site"
        tests:
          - accepted_values:
              values: ['Controls Functioning','Controls Not Functioning','Controls Obscured','No Controls Present/Factor','Not Stated']
      - name: is_county_road
        description: "If the crash occurred on a county road or not"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: is_freeway
        description: "If crash occurred on the highway or not"
        tests:
          - accepted_values:
              values: ['Yes', 'No', 'Unknown']
      - name: crash_fatal_nonfatal
        description: "Fatal if number_killed > 0 else Nonfatal"
      - name: crash_date_time
        description: "Combined crash datetime"